firewall-cmd --zone=public --add-port=0/tcp --permanent
firewall-cmd --zone=public --add-port=1004/tcp --permanent
firewall-cmd --zone=public --add-port=1006/tcp --permanent
firewall-cmd --zone=public --add-port=2181/tcp --permanent
firewall-cmd --zone=public --add-port=2888/tcp --permanent
firewall-cmd --zone=public --add-port=3181/tcp --permanent
firewall-cmd --zone=public --add-port=3888/tcp --permanent
firewall-cmd --zone=public --add-port=4181/tcp --permanent
firewall-cmd --zone=public --add-port=4867/tcp --permanent
firewall-cmd --zone=public --add-port=5768/tcp --permanent
firewall-cmd --zone=public --add-port=7077/tcp --permanent
firewall-cmd --zone=public --add-port=7078/tcp --permanent
firewall-cmd --zone=public --add-port=7180/tcp --permanent
firewall-cmd --zone=public --add-port=7182/tcp --permanent
firewall-cmd --zone=public --add-port=7183/tcp --permanent
firewall-cmd --zone=public --add-port=7184/tcp --permanent
firewall-cmd --zone=public --add-port=7185/tcp --permanent
firewall-cmd --zone=public --add-port=7186/tcp --permanent
firewall-cmd --zone=public --add-port=7187/tcp --permanent
firewall-cmd --zone=public --add-port=7432/tcp --permanent
firewall-cmd --zone=public --add-port=8002/tcp --permanent
firewall-cmd --zone=public --add-port=8003/tcp --permanent
firewall-cmd --zone=public --add-port=8019/tcp --permanent
firewall-cmd --zone=public --add-port=8020/tcp --permanent
firewall-cmd --zone=public --add-port=8021/tcp --permanent
firewall-cmd --zone=public --add-port=8030/tcp --permanent
firewall-cmd --zone=public --add-port=8031/tcp --permanent
firewall-cmd --zone=public --add-port=8032/tcp --permanent
firewall-cmd --zone=public --add-port=8033/tcp --permanent
firewall-cmd --zone=public --add-port=8040/tcp --permanent
firewall-cmd --zone=public --add-port=8041/tcp --permanent
firewall-cmd --zone=public --add-port=8042/tcp --permanent
firewall-cmd --zone=public --add-port=8080/tcp --permanent
firewall-cmd --zone=public --add-port=8083/tcp --permanent
firewall-cmd --zone=public --add-port=8084/tcp --permanent
firewall-cmd --zone=public --add-port=8085/tcp --permanent
firewall-cmd --zone=public --add-port=8086/tcp --permanent
firewall-cmd --zone=public --add-port=8087/tcp --permanent
firewall-cmd --zone=public --add-port=8088/tcp --permanent
firewall-cmd --zone=public --add-port=8091/tcp --permanent
firewall-cmd --zone=public --add-port=8480/tcp --permanent
firewall-cmd --zone=public --add-port=8485/tcp --permanent
firewall-cmd --zone=public --add-port=8888/tcp --permanent
firewall-cmd --zone=public --add-port=9000/tcp --permanent
firewall-cmd --zone=public --add-port=9001/tcp --permanent
firewall-cmd --zone=public --add-port=9010/tcp --permanent
firewall-cmd --zone=public --add-port=9083/tcp --permanent
firewall-cmd --zone=public --add-port=9090/tcp --permanent
firewall-cmd --zone=public --add-port=9095/tcp --permanent
firewall-cmd --zone=public --add-port=9290/tcp --permanent
firewall-cmd --zone=public --add-port=9994/tcp --permanent
firewall-cmd --zone=public --add-port=9995/tcp --permanent
firewall-cmd --zone=public --add-port=9996/tcp --permanent
firewall-cmd --zone=public --add-port=9997/tcp --permanent
firewall-cmd --zone=public --add-port=9998/tcp --permanent
firewall-cmd --zone=public --add-port=9999/tcp --permanent
firewall-cmd --zone=public --add-port=10000/tcp --permanent
firewall-cmd --zone=public --add-port=10020/tcp --permanent
firewall-cmd --zone=public --add-port=10101/tcp --permanent
firewall-cmd --zone=public --add-port=11000/tcp --permanent
firewall-cmd --zone=public --add-port=11001/tcp --permanent
firewall-cmd --zone=public --add-port=12000/tcp --permanent
firewall-cmd --zone=public --add-port=12001/tcp --permanent
firewall-cmd --zone=public --add-port=14000/tcp --permanent
firewall-cmd --zone=public --add-port=14001/tcp --permanent
firewall-cmd --zone=public --add-port=16000/tcp --permanent
firewall-cmd --zone=public --add-port=18080/tcp --permanent
firewall-cmd --zone=public --add-port=18081/tcp --permanent
firewall-cmd --zone=public --add-port=19888/tcp --permanent
firewall-cmd --zone=public --add-port=50010/tcp --permanent
firewall-cmd --zone=public --add-port=50020/tcp --permanent
firewall-cmd --zone=public --add-port=50030/tcp --permanent
firewall-cmd --zone=public --add-port=50060/tcp --permanent
firewall-cmd --zone=public --add-port=50070/tcp --permanent
firewall-cmd --zone=public --add-port=50075/tcp --permanent
firewall-cmd --zone=public --add-port=50090/tcp --permanent
firewall-cmd --zone=public --add-port=50470/tcp --permanent
firewall-cmd --zone=public --add-port=50495/tcp --permanent
firewall-cmd --zone=public --add-port=60000/tcp --permanent
firewall-cmd --zone=public --add-port=60010/tcp --permanent
firewall-cmd --zone=public --add-port=60020/tcp --permanent
firewall-cmd --zone=public --add-port=60030/tcp --permanent
